### ISSUE TITLE
[bug] Turtlebot3 with Gazebo on Noetic tires rotate on the wrong axis.

### ISSUE THREAD

**Issue by ooeygui** [ms-iot/ROSOnWindows#302]
**Describe the bug**
![WheelRotation](https://user-images.githubusercontent.com/4564624/99726443-5c19e400-2a6b-11eb-8db1-d6cb078fc220.gif)

**To Reproduce**
Install ROS noetic on Windows
Setup turtlebot per instructions https://ms-iot.github.io/ROSOnWindows/Turtlebot/Turtlebot3.html.

**Expected behavior**
Tires should rotate on the correct axis.

> NOTE: This does not repro on Melodic with ROS on Windows.

**Comment by seanyen** [comment]
It turned out it is a bug in SDFormat `6.2.0`. And after upgrading to the head commit from `sdf6` branch, the problem doesn't manifest again in its URDF parser.

And since the fix was out with [this sync release](https://discourse.ros.org/t/ros-on-windows-noetic-release-v20201214-0-0-2012281717/18229), I am closing it. We can reopen if it gets repro again.
