### ISSUE TITLE
How can I change ROS_MASTER_URI and ROS_IP in windows-ros

### ISSUE THREAD

**Issue by zmw654** [ms-iot/ROSOnWindows#318]
which file should I edit in the C:\opt\ros\melodic\x64 ?

**Comment by ooeygui** [comment]
Hi @zmw654 ,
I'd actually recommend setting them in your system environment or from a script you control, rather than editing files in the `c:\opt` directory. When you upgrade distributions, these modifications would be overwritten.

To set this in your environment, you can use the windows command `setx` as in:
``` bat
setx ROS_MASTER_URI=http://127.0.0.1:1331
setx ROS_IP=...
```

Then restart the command window. If you use task scheduler to start your robot, these will be picked up by the startup scripts.
