### ISSUE TITLE
Gazebo requires MSVCR100, not installed with choco

### ISSUE THREAD

**Issue by ooeygui** [ms-iot/ROSOnWindows#52]
When installing Gazebo on a clean Windows 10 Late 2018 machine, Gazebo fails because MSVCR100 is not installed. This dependency needs to be installed along with Gazebo.

**Comment by seanyen-msft** [comment]
The missing runtime are: concrt140.dll, msvcp140.dll, vcruntime140.dll.

They are not in the vanilla OS image. Since they are not only required by Gazebo, but also many other tools which have been linked with MSVC C++ runtime,  I will add this Chocolatey packages as a dependency for ros-catkin-tools.
https://chocolatey.org/packages/vcredist140
